### ISSUE TITLE
In KDE5 DESKTOP_SESSION changed from 'kde-plasma' to 'plasma'

### ISSUE THREAD

**Issue by dnebauer** [perlancar/perl-Desktop-Detect#1]
After upgrading to KDE5 ($KDE_SESSION_VERSION now = 5) I now have a bright, shiny 'plasma' desktop. Desktop::Detect no longer returns a value on my system because $DESKTOP_SESSION has changed from 'kde-plasma' to 'plasma'. At least that is the case on my system which uses kdm as display manager.

To update Desktop::Detect to continue returning 'kde-plasma' in KDE5 you could alter existing lines 45 and 46 to something like:

``` perl
last DETECT if _det_env($info, 'kde-plasma', 'XDG_DESKTOP_SESSION', qr/(kde-)?plasma/);
last DETECT if _det_env($info, 'kde-plasma', 'DESKTOP_SESSION', qr/(kde-)?plasma/);
```

Alternately, to return the new value 'plasma' you could add new lines like:

``` perl
# plasma
last DETECT if _det_env($info, 'plasma', 'XDG_DESKTOP_SESSION', 'plasma');
last DETECT if _det_env($info, 'plasma', 'DESKTOP_SESSION', 'plasma');
```

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

I've applied the second approach. A new version has been released. Thanks!
